/** Categorías de ayuda humanitaria (necesidades y oferta items). */
const CATEGORIAS = [
  'agua',
  'alimentos',
  'medicamentos',
  'aseo',
  'higiene_femenina',
  'cobijas',
  'colchonetas',
  'sabanas',
  'toallas',
  'panales',
  'formula_infantil',
  'ropa',
  'calzado',
  'toldillos',
  'linternas',
  'baterias',
  'utensilios_cocina',
  'carpas',
  'cemento',
  'ladrillos_bloques',
  'arena_grava',
  'zinc_tejas',
  'madera',
  'herramientas_construccion',
  'tuberias_electricidad',
  'pintura_impermeabilizante',
  'transporte_carga_liviana',
  'transporte_carga_pesada',
  'transporte_volqueta',
  'transporte_maquinaria',
  'transporte_pasajeros',
];

module.exports = { CATEGORIAS };
